# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b536a4cf3262217475434881e8397080ed50c0f656a289a493fe9634145a259b7f2d9a7a3a0384d9024e007638b81cf45d2b459ef4aa6433a7ff8a038de1a53

test:
  secret_key_base: 661efb424f7d8a93cdc182334efcede700931facbae90575d1e98ad10912c73d32afa6e66bb68d020f2bcab9c21c0af63dbfb210d1af9cda4b09e079a31ebb64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
